// Generated by chipchamp regmap from spec 'timer'. DO NOT EDIT.
#ifndef TIMER_REGS_H_
#define TIMER_REGS_H_

#define TIMER_CTRL_OFFSET 0x0
#define TIMER_CTRL_EN_LSB 0
#define TIMER_CTRL_EN_MASK 0x1
#define TIMER_CTRL_PRESCALE_LSB 8
#define TIMER_CTRL_PRESCALE_MASK 0xff00

#define TIMER_COUNT_OFFSET 0x4
#define TIMER_COUNT_VALUE_LSB 0
#define TIMER_COUNT_VALUE_MASK 0xffffffff

#define TIMER_STATUS_OFFSET 0x8
#define TIMER_STATUS_OVF_LSB 0
#define TIMER_STATUS_OVF_MASK 0x1

#endif  // TIMER_REGS_H_
