// Generated by chipchamp uvm — DUT-facing interface for counter.
interface counter_if #(parameter WIDTH = 8, parameter WRAP = 1'b1) (input logic clk, input logic rst_n);
  logic              en;
  logic              clr;
  logic        [7:0] count;
  logic              tc;
endinterface
