// Generated by chipchamp uvm — UVM bench top for counter.
module tb_counter_uvm;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import counter_pkg::*;

  logic clk = 0;
  logic rst_n = 1'b0;
  always #5ns clk = ~clk;

  counter_if dif (clk, rst_n);

  counter dut (.clk(dif.clk), .rst_n(dif.rst_n), .en(dif.en), .clr(dif.clr), .count(dif.count), .tc(dif.tc));

  initial begin
    repeat (4) @(posedge clk);
    rst_n = 1'b1;
  end

`ifdef CHIPCHAMP_WAVES
  initial begin
    $dumpfile("tb_counter_uvm.vcd");
    $dumpvars(0, tb_counter_uvm);
  end
`endif

  initial begin
    uvm_config_db#(virtual counter_if)::set(null, "*", "vif", dif);
    run_test("counter_smoke_test");
  end
endmodule
