"""RISC-V software toolchain: build the programs a core is verified against.

Nothing else in the vertical works without this — a compliance suite, a
directed test and a lockstep run all start as C or assembly that has to become
an ELF, a disassembly, and a memory image the testbench can ``$readmemh``.

Discovery walks PATH and the usual prefixes for a ``riscv*-gcc``. The ISA string
is explicit (``-march``/``-mabi``) because it is the *contract under test*: a
core claiming rv32imc must be exercised with rv32imc, and a toolchain without a
matching multilib has to say so rather than silently link the wrong ABI.
"""
from __future__ import annotations

import glob
import os
import re
import shutil
import subprocess
from dataclasses import dataclass

# Where distributions and the riscv-gnu-toolchain installer put things.
_PREFIX_DIRS = ("/opt/riscv/bin", "/opt/riscv32/bin", "/usr/local/riscv/bin",
                os.path.expanduser("~/riscv/bin"),
                os.path.expanduser("~/.local/riscv/bin"))
# Ordered by how likely the triple is to be a bare-metal (newlib) toolchain,
# which is what a core testbench wants — a linux-gnu gcc drags in an OS ABI.
_TRIPLES = ("riscv64-unknown-elf", "riscv32-unknown-elf", "riscv-none-elf",
            "riscv64-elf", "riscv32-elf", "riscv64-linux-gnu",
            "riscv32-linux-gnu")


@dataclass
class Toolchain:
    prefix: str = ""          # e.g. /opt/riscv/bin/riscv64-unknown-elf-
    triple: str = ""
    version: str = ""
    multilibs: list = None    # ISA variants the toolchain can actually link

    def tool(self, name: str) -> str:
        return f"{self.prefix}{name}"

    @property
    def available(self) -> bool:
        return bool(self.prefix) and shutil.which(self.tool("gcc")) is not None

    def has_multilib(self, march: str) -> bool:
        """Are there LIBRARIES (libc/libgcc) for `march`?

        Only relevant to a hosted build. `-print-multi-lib` prints '.;' for a
        single-variant toolchain — the trailing ';' separates the (empty) option
        list, so comparing against '.' misses it. A freestanding build needs no
        multilib at all: an rv64 single-multilib gcc builds rv32imac happily
        with -nostdlib, which is exactly how core test programs are built."""
        variants = [m.split(";")[0].strip() for m in (self.multilibs or [])]
        if not variants or variants == ["."]:
            return _xlen(march) == _xlen(self.default_march or march)
        return any(f"march={march}" in m for m in (self.multilibs or []))

    default_march: str = ""
    default_mabi: str = ""


def _xlen(march: str) -> int:
    m = re.match(r"rv(\d+)", (march or "").lower())
    return int(m.group(1)) if m else 64


def _run(argv: list[str], timeout: float = 60) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True, timeout=timeout)


def discover_toolchain(prefix: str = "") -> Toolchain:
    """Find a RISC-V gcc. `prefix` (a full tool prefix or a directory) wins."""
    cands: list[str] = []
    if prefix:
        if os.path.isdir(prefix):
            cands += [os.path.join(prefix, f"{t}-") for t in _TRIPLES]
        else:
            cands.append(prefix if prefix.endswith("-") else prefix + "-")
    for d in ("",) + _PREFIX_DIRS:
        for t in _TRIPLES:
            cands.append(os.path.join(d, f"{t}-") if d else f"{t}-")
    for cand in cands:
        gcc = f"{cand}gcc"
        if shutil.which(gcc) is None:
            continue
        tc = Toolchain(prefix=cand, triple=os.path.basename(cand).rstrip("-"))
        try:
            v = _run([gcc, "--version"], timeout=20)
            tc.version = (v.stdout or "").splitlines()[0] if v.stdout else ""
            ml = _run([gcc, "-print-multi-lib"], timeout=20)
            tc.multilibs = [ln.strip() for ln in (ml.stdout or "").splitlines()
                            if ln.strip()]
            q = _run([gcc, "-Q", "--help=target"], timeout=25)
            for line in (q.stdout or "").splitlines():
                m = re.match(r"\s*-march=\s+(\S+)", line)
                if m and not tc.default_march:
                    tc.default_march = m.group(1)
                m = re.match(r"\s*-mabi=\s+(\S+)", line)
                if m and not tc.default_mabi:
                    tc.default_mabi = m.group(1)
        except (OSError, subprocess.SubprocessError):
            pass
        return tc
    return Toolchain()


def default_abi(march: str) -> str:
    """The ABI that matches an ISA string: rv32* -> ilp32[f|d], rv64* -> lp64[f|d]."""
    base = "ilp32" if _xlen(march) == 32 else "lp64"
    ext = (march or "").lower()
    if "d" in ext.split("_")[0][4:]:
        return base + "d"
    if "f" in ext.split("_")[0][4:]:
        return base + "f"
    return base


DEFAULT_LINKER_SCRIPT = """\
/* generated by chipchamp — flat bare-metal image for a core testbench */
ENTRY(_start)
SECTIONS
{{
  . = {base};
  .text   : {{ *(.text.init) *(.text*) }}
  .rodata : {{ *(.rodata*) *(.srodata*) }}
  .data   : {{ *(.data*) *(.sdata*) }}
  .bss    : {{ *(.bss*) *(.sbss*) *(COMMON) }}
  _end = .;
}}
"""


def write_linker_script(path: str, base: str = "0x80000000") -> str:
    with open(path, "w") as fh:
        fh.write(DEFAULT_LINKER_SCRIPT.format(base=base))
    return path


def compile_argv(tc: Toolchain, sources: list[str], out_elf: str, *,
                 march: str = "rv32i", mabi: str = "", ldscript: str = "",
                 includes: list[str] | None = None,
                 defines: dict | None = None, opt: str = "-O2",
                 freestanding: bool = True, extra: list[str] | None = None
                 ) -> list[str]:
    argv = [tc.tool("gcc"), f"-march={march}", f"-mabi={mabi or default_abi(march)}",
            opt, "-g"]
    if freestanding:
        # a core testbench has no OS and no startup files
        argv += ["-nostdlib", "-nostartfiles", "-ffreestanding"]
    for d in (includes or []):
        argv.append(f"-I{d}")
    for k, v in (defines or {}).items():
        argv.append(f"-D{k}={v}" if v not in (None, "") else f"-D{k}")
    if ldscript:
        argv += ["-T", ldscript]
    argv += list(extra or [])
    argv += list(sources)
    argv += ["-o", out_elf]
    return argv


# ---- ELF introspection -------------------------------------------------------------


def elf_symbols(tc: Toolchain, elf: str) -> dict:
    """{symbol: address}. Test harnesses key off these (tohost, _start, pass/fail)."""
    out: dict = {}
    try:
        r = _run([tc.tool("nm"), "-n", elf], timeout=30)
    except (OSError, subprocess.SubprocessError):
        return out
    for line in (r.stdout or "").splitlines():
        parts = line.split()
        if len(parts) == 3 and re.fullmatch(r"[0-9a-fA-F]+", parts[0]):
            out[parts[2]] = int(parts[0], 16)
    return out


def elf_sections(tc: Toolchain, elf: str) -> list[dict]:
    """[{name, addr, size}] — enough to know where the image must be loaded."""
    secs: list[dict] = []
    try:
        r = _run([tc.tool("readelf"), "-S", "-W", elf], timeout=30)
    except (OSError, subprocess.SubprocessError):
        return secs
    for line in (r.stdout or "").splitlines():
        m = re.match(r"\s*\[\s*\d+\]\s+(\S+)\s+(\S+)\s+([0-9a-fA-F]+)\s+"
                     r"([0-9a-fA-F]+)\s+([0-9a-fA-F]+)", line)
        if m and m.group(1) != "NULL":
            secs.append({"name": m.group(1), "addr": int(m.group(3), 16),
                         "size": int(m.group(5), 16)})
    return secs


def elf_xlen(tc: Toolchain, elf: str) -> int:
    """32 or 64 from the ELF header. The reference model must be told the XLEN:
    spike defaults to rv64 and simply refuses a 32-bit payload, which surfaces
    as an empty trace unless we pass --isa."""
    try:
        r = _run([tc.tool("readelf"), "-h", elf], timeout=20)
    except (OSError, subprocess.SubprocessError):
        return 0
    for line in (r.stdout or "").splitlines():
        if "Class:" in line:
            return 32 if "ELF32" in line else 64 if "ELF64" in line else 0
    return 0


def isa_for_elf(tc: Toolchain, elf: str) -> str:
    """A permissive ISA string matching the ELF's XLEN. A superset is safe: a
    core's rv32i program runs unchanged on an rv32imafdc model."""
    x = elf_xlen(tc, elf)
    if not x:
        return ""
    return "rv32imafdc_zicsr_zifencei" if x == 32 else "rv64imafdc_zicsr_zifencei"


def disassemble(tc: Toolchain, elf: str, max_lines: int = 400) -> str:
    try:
        r = _run([tc.tool("objdump"), "-d", "-M", "numeric", elf], timeout=60)
    except (OSError, subprocess.SubprocessError) as e:
        return f"(objdump failed: {e})"
    lines = (r.stdout or "").splitlines()
    if len(lines) > max_lines:
        lines = lines[:max_lines] + [f"…[truncated {len(lines) - max_lines} lines]"]
    return "\n".join(lines)


def elf_to_hex(tc: Toolchain, elf: str, out_hex: str, *, width: int = 32,
               base: int | None = None) -> dict:
    """ELF -> a `$readmemh` image: one WORD per line, little-endian, so a
    testbench can load it straight into a memory array. Returns {words, base,
    bytes}."""
    if width % 8 or width <= 0:
        raise ValueError("width must be a positive multiple of 8")
    tmp_bin = out_hex + ".bin"
    r = _run([tc.tool("objcopy"), "-O", "binary", elf, tmp_bin], timeout=60)
    if r.returncode != 0:
        raise RuntimeError(f"objcopy failed: {(r.stderr or '').strip()[:200]}")
    with open(tmp_bin, "rb") as fh:
        blob = fh.read()
    os.remove(tmp_bin)
    nbytes = width // 8
    if len(blob) % nbytes:                      # pad the tail word
        blob += b"\x00" * (nbytes - len(blob) % nbytes)
    words = [blob[i:i + nbytes] for i in range(0, len(blob), nbytes)]
    if base is None:
        secs = [s for s in elf_sections(tc, elf) if s["size"] and s["addr"]]
        base = min((s["addr"] for s in secs), default=0)
    with open(out_hex, "w") as fh:
        fh.write(f"// generated by chipchamp from {os.path.basename(elf)} — "
                 f"{width}-bit words, little-endian, load address "
                 f"0x{base:08x}\n")
        for w in words:
            fh.write(int.from_bytes(w, "little").to_bytes(nbytes, "big").hex()
                     + "\n")
    return {"words": len(words), "base": base, "bytes": len(blob)}


# ---- reference model (ISS) ---------------------------------------------------------

# The gdb/binutils RISC-V simulator ships WITH the toolchain (…-run), so a
# reference model is available wherever gcc is. Spike is the canonical choice
# when installed; both are normalized to the same trace shape by trace.py.
_ISS_BACKENDS = ("spike", "gdbsim")


def find_iss(tc: Toolchain, prefer: str = "") -> tuple[str, str]:
    """(backend, executable). Prefers spike when present — it is the reference
    implementation — and falls back to the toolchain's own simulator."""
    order = ([prefer] if prefer else []) + list(_ISS_BACKENDS)
    for backend in order:
        if backend == "spike":
            exe = shutil.which("spike")
            if exe:
                return "spike", exe
        elif backend == "gdbsim":
            exe = shutil.which(tc.tool("run")) if tc.prefix else None
            if exe:
                return "gdbsim", exe
    return "", ""


def run_iss_bounded(argv: list[str], *, max_lines: int = 20000,
                    timeout: float = 60.0) -> tuple[str, bool, bool]:
    """Run a tracing ISS and stop at `max_lines` of output or `timeout`.

    Bare-metal test programs conventionally END IN A SPIN LOOP, so a model with
    no instruction limit (the gdb simulator has none) would run until killed and
    a plain `subprocess.run` would then discard everything it printed. Stream
    instead, keep what arrived, and stop deliberately.

    Returns (text, hit_line_limit, timed_out)."""
    import threading
    proc = subprocess.Popen(argv, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True,
                            errors="replace", bufsize=1)
    lines: list[str] = []
    hit_limit = threading.Event()

    def reader():
        try:
            for line in proc.stdout:            # type: ignore[union-attr]
                lines.append(line)
                if len(lines) >= max_lines:
                    hit_limit.set()
                    break
        except Exception:
            pass

    t = threading.Thread(target=reader, daemon=True)
    t.start()
    t.join(timeout)
    timed_out = t.is_alive() and not hit_limit.is_set()
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
    t.join(timeout=2)
    try:
        if proc.stdout:
            proc.stdout.close()
    except Exception:
        pass
    return "".join(lines), hit_limit.is_set(), timed_out


def iss_argv(backend: str, exe: str, elf: str, *, march: str = "",
             max_steps: int = 0, regions: list[str] | None = None,
             harts: int = 0) -> list[str]:
    if backend == "spike":
        # -l disassembles each instruction; --log-commits adds the
        # architectural writeback, which upgrades cosim from PC-lockstep to
        # register-level lockstep. Both are folded into one step by trace.py.
        argv = [exe, "-l", "--log-commits"]
        if march:
            argv.append(f"--isa={march}")
        if max_steps:
            argv.append(f"--instructions={max_steps}")
        if harts > 1:
            # a barrel core's threads each have their own mhartid; a program
            # that branches on it needs one reference stream PER hart
            argv.append(f"-p{harts}")
        return argv + [elf]
    argv = [exe, "--trace-insn=on", "--trace-disasm=on"]
    for r in (regions or []):
        argv += ["--memory-region", r]
    return argv + [elf]
