"""Vivado adapter — real design checkpoints (SPEC §8.4 FPGA vertical,
vendor path).

Non-project batch flow writing a ``.dcp`` at every stage — ``post_synth`` →
``post_place`` → ``post_route`` — each with ``report_timing_summary`` /
``report_utilization`` (+ power and worst paths post-route). Checkpoints are
the vendor-native currency: any of them re-opens in Vivado for deeper
analysis; chipchamp's job record keeps the normalized metrics per stage.

Discovery: ``vivado`` on PATH, ``$XILINX_VIVADO``, or ``~/Xilinx/*/Vivado``.
"""
from __future__ import annotations

import glob
import os
import shutil

from .base import (Adapter, CapabilityManifest, NormalizedDiagnostic, Plan,
                   Step, StepResult, ToolResult)

_STAGES = ("post_synth", "post_place", "post_route")


def _find_vivado() -> str | None:
    if shutil.which("vivado"):
        return "vivado"
    env = os.environ.get("XILINX_VIVADO", "")
    if env:
        cand = os.path.join(env, "bin", "vivado")
        if os.path.exists(cand):
            return cand
    hits = sorted(glob.glob(os.path.expanduser("~/Xilinx/*/Vivado/bin/vivado")))
    return hits[-1] if hits else None


_FLOW_TCL = """\
# generated by chipchamp — FPGA checkpoint flow (non-project batch)
set_msg_config -severity INFO -suppress
{reads}
{xdc}synth_design -top {top} -part {part}{ooc}
create_clock -period {period} -name {clk} [get_ports {clk}]
write_checkpoint -force {ckpt}/post_synth.dcp
report_timing_summary -file {ckpt}/post_synth.timing.rpt
report_utilization -file {ckpt}/post_synth.util.rpt
opt_design
place_design
write_checkpoint -force {ckpt}/post_place.dcp
report_timing_summary -file {ckpt}/post_place.timing.rpt
report_utilization -file {ckpt}/post_place.util.rpt
route_design
write_checkpoint -force {ckpt}/post_route.dcp
report_timing_summary -file {ckpt}/post_route.timing.rpt
report_utilization -file {ckpt}/post_route.util.rpt
report_power -file {ckpt}/post_route.power.rpt
report_timing -max_paths {npaths} -nworst 1 -file {ckpt}/post_route.paths.rpt
"""


class VivadoAdapter(Adapter):
    name = "vivado"
    binary = "vivado"
    cost = "metered"  # long-running; WebPACK parts need no license feature

    def available(self) -> bool:
        return _find_vivado() is not None

    def version(self) -> str:
        vv = _find_vivado()
        if not vv:
            return "not-installed"
        import subprocess
        try:
            out = subprocess.run([vv, "-version"], capture_output=True,
                                 text=True, timeout=120)
            first = (out.stdout or out.stderr).strip().splitlines()
            return first[0] if first else "unknown"
        except (OSError, subprocess.SubprocessError):
            return "unknown"

    def manifest(self) -> CapabilityManifest:
        return CapabilityManifest(
            name=self.name, roles=["fpga"], languages=["sv", "vhdl"],
            standards=["xilinx-7series", "ultrascale", "dcp"],
            known_gaps=["needs a licensed part for non-WebPACK devices",
                        "OOC default (pin constraints are a project artifact)"])

    def fpga_flow(self, files: list[str], top: str, workdir: str,
                  part: str = "xc7a35tcpg236-1", clock_port: str = "clk",
                  clock_period_ns: float = 10.0, out_of_context: bool = True,
                  max_paths: int = 3, xdc: str = "") -> Plan:
        vv = _find_vivado() or "vivado"
        ckpt = os.path.abspath(os.path.join(workdir, "checkpoints"))
        os.makedirs(ckpt, exist_ok=True)
        reads = "\n".join(
            (f"read_vhdl {f}" if f.endswith((".vhd", ".vhdl"))
             else f"read_verilog -sv {f}") for f in files)
        tcl = _FLOW_TCL.format(
            reads=reads, top=top, part=part,
            # pin/IOSTANDARD constraints: without them Vivado's UCIO-1/NSTD-1
            # DRCs block write_bitstream, so a bitstream run needs an XDC.
            xdc=f"read_xdc {xdc}\n" if xdc else "",
            ooc=" -mode out_of_context" if out_of_context else "",
            period=clock_period_ns, clk=clock_port, ckpt=ckpt,
            npaths=max_paths)
        tcl_path = os.path.join(ckpt, "flow.tcl")
        with open(tcl_path, "w") as fh:
            fh.write(tcl)
        argv = [vv, "-mode", "batch", "-source", tcl_path, "-nojournal",
                "-log", os.path.join(ckpt, "vivado.log")]
        artifacts = {"tcl": tcl_path}
        for st in _STAGES:
            artifacts[f"{st}_dcp"] = os.path.join(ckpt, f"{st}.dcp")
            artifacts[f"{st}_timing"] = os.path.join(ckpt, f"{st}.timing.rpt")
            artifacts[f"{st}_util"] = os.path.join(ckpt, f"{st}.util.rpt")
        artifacts["post_route_power"] = os.path.join(ckpt, "post_route.power.rpt")
        artifacts["post_route_paths"] = os.path.join(ckpt, "post_route.paths.rpt")
        return Plan(kind="fpga", adapter=self.name, workdir=workdir,
                    steps=[Step(argv=argv, cwd=workdir, allow_fail=True)],
                    artifacts=artifacts,
                    meta={"top": top, "part": part, "flow": "vivado",
                          "clock_period_ns": clock_period_ns,
                          # a bitstream needs a full (non-OOC) implementation —
                          # recorded so fpga.bitstream can say so up front
                          "out_of_context": bool(out_of_context)})

    def packer_for(self, family: str = "") -> str:
        return "write_bitstream"

    def pack_flow(self, config: str, family: str, workdir: str,
                  top: str = "") -> Plan:
        """Bitstream from a routed checkpoint (`config` is the post_route .dcp)."""
        vv = _find_vivado() or "vivado"
        ckpt = os.path.dirname(config) or os.path.join(workdir, "checkpoints")
        bitstream = os.path.join(ckpt, f"{top or 'design'}.bit")
        tcl_path = os.path.join(ckpt, "bitstream.tcl")
        with open(tcl_path, "w") as fh:
            fh.write("# generated by chipchamp — bitstream from a routed dcp\n"
                     f"open_checkpoint {config}\n"
                     f"write_bitstream -force {bitstream}\n")
        argv = [vv, "-mode", "batch", "-source", tcl_path, "-nojournal",
                "-log", os.path.join(ckpt, "bitstream.log")]
        return Plan(kind="fpga_bitstream", adapter=self.name, workdir=workdir,
                    steps=[Step(argv=argv, cwd=workdir, allow_fail=True)],
                    artifacts={"bitstream": bitstream, "tcl": tcl_path,
                               "bitstream_config": config},
                    meta={"top": top, "flow": "vivado",
                          "packer": "write_bitstream"})

    def _parse_pack(self, plan: Plan, results: list[StepResult]) -> ToolResult:
        run = results[0] if results else None
        bit = plan.artifacts.get("bitstream", "")
        size = os.path.getsize(bit) if os.path.exists(bit) else 0
        ok = bool(run and run.rc == 0 and size > 0)
        diags: list[NormalizedDiagnostic] = []
        log = ((run.stdout + "\n" + run.stderr) if run else "")
        if not os.path.exists(plan.artifacts.get("bitstream", "x")):
            log += _read(os.path.join(
                os.path.dirname(plan.artifacts.get("tcl", "")), "bitstream.log"))
        # The classic first-bitstream failure: every top-level port needs a LOC
        # (UCIO-1) and an IOSTANDARD (NSTD-1). Name it instead of "see the log".
        needs_pins = "DRC UCIO-1" in log or "DRC NSTD-1" in log
        if not ok:
            err = [ln for ln in log.splitlines() if ln.startswith("ERROR:")]
            diags.append(NormalizedDiagnostic(
                tool="vivado", severity="error", category="fpga",
                code="PIN-CONSTRAINTS" if needs_pins else "PACK",
                message=(("top-level ports have no pin (LOC) / IOSTANDARD "
                          "constraints — Vivado blocks bitstream generation")
                         if needs_pins else
                         (err[-1] if err else
                          "write_bitstream produced no bitstream"))[:200]))
        return ToolResult(
            ok=ok, kind="fpga_bitstream", adapter=self.name,
            status="pass" if ok else "fail", diagnostics=diags,
            artifacts={k: v for k, v in plan.artifacts.items()
                       if os.path.exists(v)},
            metrics={"top": plan.meta.get("top"), "flow": "vivado",
                     "packer": "write_bitstream", "bitstream_bytes": size,
                     "needs_pin_constraints": needs_pins},
            summary=(f"write_bitstream: {size} byte bitstream" if ok
                     else "write_bitstream blocked: unconstrained pins"
                     if needs_pins
                     else "write_bitstream failed — see bitstream.log"))

    def parse(self, plan: Plan, results: list[StepResult]) -> ToolResult:
        from ..physical.fpga import (parse_vivado_power,
                                     parse_vivado_timing_summary,
                                     parse_vivado_utilization)
        if plan.kind == "fpga_bitstream":
            return self._parse_pack(plan, results)
        diags: list[NormalizedDiagnostic] = []
        run = results[0]
        log = run.stdout + "\n" + run.stderr
        for ln in log.splitlines():
            if ln.startswith(("ERROR:", "CRITICAL WARNING:")):
                diags.append(NormalizedDiagnostic(
                    tool="vivado", severity="error" if ln.startswith("ERROR")
                    else "warning", category="fpga",
                    code=ln.split(" ")[0].rstrip(":"), message=ln[:200]))
        stages: list[str] = []
        metrics: dict = {"part": plan.meta.get("part"),
                         "top": plan.meta.get("top"),
                         "clock_period_ns": plan.meta.get("clock_period_ns"),
                         "flow": "vivado",
                         # carried into the job record so fpga.bitstream knows
                         # whether this run can produce a bitstream at all
                         "out_of_context": plan.meta.get("out_of_context", True)}
        for st in _STAGES:
            if not os.path.exists(plan.artifacts.get(f"{st}_dcp", "")):
                continue
            stages.append(st)
            t = _read(plan.artifacts.get(f"{st}_timing", ""))
            u = _read(plan.artifacts.get(f"{st}_util", ""))
            if t:
                for k, v in parse_vivado_timing_summary(t).items():
                    metrics[f"{st}.{k}"] = v
            if u:
                for res, vv in parse_vivado_utilization(u).items():
                    metrics[f"{st}.{res}_used"] = vv["used"]
                    metrics[f"{st}.{res}_avail"] = vv["available"]
        p = _read(plan.artifacts.get("post_route_power", ""))
        if p:
            metrics.update({f"post_route.{k}": v
                            for k, v in parse_vivado_power(p).items()})
        metrics["stages"] = stages
        routed = "post_route" in stages
        wns = metrics.get("post_route.wns_ns")
        whs = metrics.get("post_route.whs_ns")
        timing_met = (wns is None or wns >= 0) and (whs is None or whs >= 0)
        metrics["timing_met"] = timing_met if routed else False
        ok = routed and timing_met and run.rc == 0
        status = "pass" if ok else ("fail" if routed else "error")
        summary = (f"vivado {plan.meta.get('part')}: {len(stages)} checkpoint(s); "
                   f"WNS {wns} ns, WHS {whs} ns — "
                   f"{'timing met' if timing_met else 'TIMING FAILED'}"
                   if routed else
                   f"flow stopped after {stages or ['(nothing)']}"
                   f" — see vivado.log")
        artifacts = {k: v for k, v in plan.artifacts.items() if os.path.exists(v)}
        return ToolResult(ok=ok, kind="fpga", adapter=self.name, status=status,
                          diagnostics=diags[:12], artifacts=artifacts,
                          metrics=metrics, summary=summary)


def _read(path: str) -> str:
    try:
        with open(path, "r", errors="replace") as fh:
            return fh.read()
    except OSError:
        return ""
