"""Generate a complete, compilable UVM bench from a design-database module.

Deterministic like the regmap compiler: module in → dict of files out
(interface, seq_item, sequencer, driver, monitor, agent, scoreboard stub, env,
sequences, base+smoke test, tb top, package, filelist). The scaffold is a
starting point that already runs — reset, clocking, config_db plumbing and the
UVM report plumbing are wired; the reference model in the scoreboard is the
part that stays human/agent work (marked TODO).

Runs on the license-free path out of the box: Verilator 5 + Accellera
uvm-core (``adapters.uvm.uvm_home``), and unchanged on Questa/VCS.
"""
from __future__ import annotations

def _waves_macro() -> str:
    """Waves-gate macro for GENERATED benches (current brand; the
    adapters define legacy brands' macros too, so either era dumps)."""
    from ..brand import marker
    return marker("WAVES")


import re
from dataclasses import dataclass

_CLK = re.compile(r"^(clk|clock)(_\w+)?$|_clk$|_clock$", re.IGNORECASE)
_RST = re.compile(r"^(rst|reset)(_?n)?(_\w+)?$|_rst_?n?$|_reset$", re.IGNORECASE)


@dataclass
class _P:
    name: str
    direction: str
    width: str  # "" for scalar, else e.g. "[WIDTH-1:0]"


def _classify(mod):
    clk = rst = None
    ins, outs = [], []
    for p in mod.ports:
        w = p.width_expr or (f"[{p.msb}:{p.lsb}]" if p.msb is not None else "")
        q = _P(p.name, p.direction, w)
        if p.direction == "input" and clk is None and _CLK.search(p.name):
            clk = q
            continue
        if p.direction == "input" and rst is None and _RST.search(p.name):
            rst = q
            continue
        (ins if p.direction == "input" else outs).append(q)
    return clk, rst, ins, outs


def _params_decl(mod) -> str:
    ps = [p for p in getattr(mod, "params", []) if not p.is_localparam]
    if not ps:
        return ""
    inner = ", ".join(f"parameter {p.name} = {p.default_expr or '1'}" for p in ps)
    return f" #({inner})"




def scaffold_uvm(mod, active_low_reset: bool | None = None) -> dict[str, str]:
    """{relative_path: content} for a UVM bench of ``mod`` (a design-db
    Module). Paths are relative to a bench root, e.g. ``verif/uvm/<name>/``."""
    m = mod.name
    clk, rst, ins, outs = _classify(mod)
    if active_low_reset is None:
        active_low_reset = bool(rst and rst.name.rstrip().endswith(("n", "N")))
    clk_n = clk.name if clk else "clk"
    rst_n = rst.name if rst else "rst_n"
    rst_off = "1'b1" if active_low_reset else "1'b0"
    rst_on = "1'b0" if active_low_reset else "1'b1"
    pdecl = _params_decl(mod)
    # DUT + interface are instantiated at their parameter DEFAULTS: the bench
    # must elaborate standalone. Sweep configs by overriding here.
    pmap = ""

    sig_decls = "\n".join(f"  logic {p.width:>12} {p.name};"
                          for p in ins + outs) or "  // (no data ports)"
    drive_defaults = "\n".join(f"    vif.{p.name} <= '0;" for p in ins)
    drive_items = "\n".join(f"      vif.{p.name} <= req.{p.name};" for p in ins)
    rand_fields = "\n".join(f"  rand logic {p.width:>12} {p.name};" for p in ins)
    field_macros = "\n".join(f"    `uvm_field_int({p.name}, UVM_ALL_ON)"
                             for p in ins + outs)
    obs_fields = "\n".join(f"  logic {p.width:>12} {p.name};" for p in outs)
    mon_sample = "\n".join(f"      tr.{p.name} = vif.{p.name};"
                           for p in ins + outs)
    dut_conns = ", ".join([f".{clk_n}(dif.{clk_n})" if clk else "",
                           f".{rst_n}(dif.{rst_n})" if rst else ""]
                          + [f".{p.name}(dif.{p.name})" for p in ins + outs])
    dut_conns = ", ".join(x for x in dut_conns.split(", ") if x)

    files: dict[str, str] = {}

    files[f"{m}_if.sv"] = f"""\
// Generated by chipchamp uvm — DUT-facing interface for {m}.
interface {m}_if{pdecl} (input logic {clk_n}, input logic {rst_n});
{sig_decls}
endinterface
"""

    files[f"{m}_seq_item.sv"] = f"""\
class {m}_seq_item extends uvm_sequence_item;
{rand_fields or '  // (no stimulus fields: DUT has no data inputs)'}
{obs_fields or ''}
  `uvm_object_utils_begin({m}_seq_item)
{field_macros}
  `uvm_object_utils_end

  function new(string name = "{m}_seq_item");
    super.new(name);
  endfunction
  // TODO: add protocol constraints (legal opcodes, aligned addresses, ...)
endclass
"""

    files[f"{m}_sequencer.sv"] = f"""\
typedef uvm_sequencer#({m}_seq_item) {m}_sequencer;
"""

    files[f"{m}_driver.sv"] = f"""\
class {m}_driver extends uvm_driver#({m}_seq_item);
  `uvm_component_utils({m}_driver)
  virtual {m}_if vif;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual {m}_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "no virtual interface for driver")
  endfunction

  task run_phase(uvm_phase phase);
{drive_defaults or '    // no inputs to initialize'}
    @(posedge vif.{rst_n} iff vif.{rst_n} == {rst_off});
    forever begin
      seq_item_port.get_next_item(req);
      @(posedge vif.{clk_n});
{drive_items or '      // no inputs to drive'}
      seq_item_port.item_done();
    end
  endtask
endclass
"""

    files[f"{m}_monitor.sv"] = f"""\
class {m}_monitor extends uvm_monitor;
  `uvm_component_utils({m}_monitor)
  virtual {m}_if vif;
  uvm_analysis_port#({m}_seq_item) ap;

  function new(string name, uvm_component parent);
    super.new(name, parent);
    ap = new("ap", this);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(virtual {m}_if)::get(this, "", "vif", vif))
      `uvm_fatal("NOVIF", "no virtual interface for monitor")
  endfunction

  task run_phase(uvm_phase phase);
    {m}_seq_item tr;
    forever begin
      @(posedge vif.{clk_n});
      if (vif.{rst_n} != {rst_off}) continue;
      tr = {m}_seq_item::type_id::create("tr");
{mon_sample or '      // nothing to sample'}
      ap.write(tr);
    end
  endtask
endclass
"""

    files[f"{m}_agent.sv"] = f"""\
class {m}_agent extends uvm_agent;
  `uvm_component_utils({m}_agent)
  {m}_driver    drv;
  {m}_sequencer sqr;
  {m}_monitor   mon;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    mon = {m}_monitor::type_id::create("mon", this);
    if (get_is_active() == UVM_ACTIVE) begin
      drv = {m}_driver::type_id::create("drv", this);
      sqr = {m}_sequencer::type_id::create("sqr", this);
    end
  endfunction

  function void connect_phase(uvm_phase phase);
    if (get_is_active() == UVM_ACTIVE)
      drv.seq_item_port.connect(sqr.seq_item_export);
  endfunction
endclass
"""

    files[f"{m}_scoreboard.sv"] = f"""\
class {m}_scoreboard extends uvm_subscriber#({m}_seq_item);
  `uvm_component_utils({m}_scoreboard)
  int unsigned n_seen;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void write({m}_seq_item t);
    n_seen++;
    // TODO reference model: compute expected outputs from t's inputs and
    // compare — `uvm_error on mismatch. The monitor already samples
    // {', '.join(p.name for p in outs) or 'the DUT state'}.
  endfunction

  function void report_phase(uvm_phase phase);
    if (n_seen == 0)
      `uvm_error("SB_EMPTY", "scoreboard saw no transactions")
    else
      `uvm_info("SB", $sformatf("%0d transactions observed", n_seen), UVM_LOW)
  endfunction
endclass
"""

    files[f"{m}_env.sv"] = f"""\
class {m}_env extends uvm_env;
  `uvm_component_utils({m}_env)
  {m}_agent      agt;
  {m}_scoreboard sb;

  function new(string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    agt = {m}_agent::type_id::create("agt", this);
    sb  = {m}_scoreboard::type_id::create("sb", this);
  endfunction

  function void connect_phase(uvm_phase phase);
    agt.mon.ap.connect(sb.analysis_export);
  endfunction
endclass
"""

    files[f"{m}_seq_lib.sv"] = f"""\
class {m}_base_seq extends uvm_sequence#({m}_seq_item);
  `uvm_object_utils({m}_base_seq)
  rand int unsigned n_items = 20;
  constraint c_n {{ n_items inside {{[10:50]}}; }}

  function new(string name = "{m}_base_seq");
    super.new(name);
  endfunction

  task body();
    repeat (n_items) begin
      req = {m}_seq_item::type_id::create("req");
      start_item(req);
      if (!req.randomize())
        `uvm_error("RANDFAIL", "seq_item randomization failed")
      finish_item(req);
    end
  endtask
endclass
"""

    files[f"{m}_test_lib.sv"] = f"""\
class {m}_base_test extends uvm_test;
  `uvm_component_utils({m}_base_test)
  {m}_env env;

  function new(string name = "{m}_base_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    env = {m}_env::type_id::create("env", this);
  endfunction

  task run_phase(uvm_phase phase);
    {m}_base_seq seq;
    phase.raise_objection(this);
    seq = {m}_base_seq::type_id::create("seq");
    if (!seq.randomize()) `uvm_error("RANDFAIL", "seq randomization failed")
    seq.start(env.agt.sqr);
    #100ns;
    phase.drop_objection(this);
  endtask
endclass

class {m}_smoke_test extends {m}_base_test;
  `uvm_component_utils({m}_smoke_test)
  function new(string name = "{m}_smoke_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction
endclass
"""

    files[f"{m}_pkg.sv"] = f"""\
package {m}_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  `include "{m}_seq_item.sv"
  `include "{m}_sequencer.sv"
  `include "{m}_driver.sv"
  `include "{m}_monitor.sv"
  `include "{m}_agent.sv"
  `include "{m}_scoreboard.sv"
  `include "{m}_env.sv"
  `include "{m}_seq_lib.sv"
  `include "{m}_test_lib.sv"
endpackage
"""

    files[f"tb_{m}_uvm.sv"] = f"""\
// Generated by chipchamp uvm — UVM bench top for {m}.
module tb_{m}_uvm;
  import uvm_pkg::*;
  `include "uvm_macros.svh"
  import {m}_pkg::*;

  logic {clk_n} = 0;
  logic {rst_n} = {rst_on};
  always #5ns {clk_n} = ~{clk_n};

  {m}_if dif ({clk_n}, {rst_n});

  {m}{pmap} dut ({dut_conns});

  initial begin
    repeat (4) @(posedge {clk_n});
    {rst_n} = {rst_off};
  end

`ifdef {_waves_macro()}
  initial begin
    $dumpfile("tb_{m}_uvm.vcd");
    $dumpvars(0, tb_{m}_uvm);
  end
`endif

  initial begin
    uvm_config_db#(virtual {m}_if)::set(null, "*", "vif", dif);
    run_test("{m}_smoke_test");
  end
endmodule
"""

    files[f"{m}_uvm.f"] = f"""\
// chipchamp uvm filelist for {m} (paths relative to this bench dir)
+incdir+.
{m}_pkg.sv
tb_{m}_uvm.sv
"""
    return files
