"""Activity-driven power analysis (the P in PPA, done honestly).

Vectorless power (what ``metrics.json`` reports) assumes a default toggle
probability on every net — a guess. This module annotates the **routed**
netlist with switching activity from a real workload VCD (the waveform the
sim jobs already dump), runs OpenSTA's ``report_power`` (the same OpenSTA
that rides in the LibreLane devshell), and reports:

- power by group (sequential/combinational/clock/pad × internal/switching/
  leakage) — the clock-tree share is the clock-gating signal;
- the hottest instances, cross-probed back to RTL nets via the netlist;
- the **annotation rate** (``report_activity_annotation``) so a low-match
  VCD can't masquerade as a trustworthy number.
"""
from __future__ import annotations

import os
import re

# ---- VCD scope discovery ---------------------------------------------------------

_SCOPE = re.compile(r"\$scope\s+\w+\s+(\S+)\s+\$end")
_UPSCOPE = re.compile(r"\$upscope")
_VAR = re.compile(r"\$var\s+\w+\s+\d+\s+\S+\s+(\S+)")


def find_dut_scope(vcd_path: str, port_names: set[str],
                   max_lines: int = 20000) -> str | None:
    """The hierarchical scope inside the VCD whose variables look like the
    DUT's ports — where ``read_power_activities -scope`` should point."""
    stack: list[str] = []
    scores: dict[str, int] = {}
    try:
        with open(vcd_path, "r", errors="replace") as fh:
            for i, ln in enumerate(fh):
                if i > max_lines or "$enddefinitions" in ln:
                    break
                m = _SCOPE.search(ln)
                if m:
                    stack.append(m.group(1))
                    continue
                if _UPSCOPE.search(ln):
                    if stack:
                        stack.pop()
                    continue
                m = _VAR.search(ln)
                if m and stack and m.group(1).split("[")[0] in port_names:
                    scores["/".join(stack)] = scores.get("/".join(stack), 0) + 1
    except OSError:
        return None
    if not scores:
        return None
    # most port-matching vars wins; deeper scope breaks ties (tb wraps dut)
    return max(scores, key=lambda s: (scores[s], s.count("/")))


def find_cell_models() -> list[str] | None:
    """Simulation models for the standard cells (gate-level sim):
    $CHIPCHAMP_CELL_MODELS (colon-separated) or the ciel-managed sky130 HD
    verilog (primitives.v + sky130_fd_sc_hd.v, compiled with FUNCTIONAL)."""
    import glob as _glob
    from ..brand import env as benv
    env = benv("CELL_MODELS", "")
    if env:
        files = [f for f in env.split(":") if os.path.exists(f)]
        return files or None
    for pat in ("~/.ciel/ciel/sky130/versions/*/sky130A/libs.ref/"
                "sky130_fd_sc_hd/verilog",
                "~/.ciel/ciel/sky130/versions/*/sky130B/libs.ref/"
                "sky130_fd_sc_hd/verilog"):
        hits = sorted(_glob.glob(os.path.expanduser(pat)))
        if hits:
            v = hits[-1]
            files = [os.path.join(v, "primitives.v"),
                     os.path.join(v, "sky130_fd_sc_hd.v")]
            if all(os.path.exists(f) for f in files):
                return files
    return None


# ---- STA script ------------------------------------------------------------------

POWER_TCL = """\
# generated by chipchamp — activity-driven power (OpenSTA)
read_liberty {liberty}
read_verilog {netlist}
link_design {top}
{read_spef}
create_clock -name {clock} -period {period} [get_ports {clock}]
{activities}
puts "== CHIPCHAMP ANNOTATION =="
report_activity_annotation -report_unannotated
puts "== CHIPCHAMP POWER =="
report_power -digits 6
puts "== CHIPCHAMP INSTANCES =="
report_power -highest_power_instances {n_hot} -digits 6
puts "== CHIPCHAMP DONE =="
"""


def power_tcl(*, liberty: str, netlist: str, top: str, clock: str,
              period_ns: float, spef: str = "", vcd: str = "",
              scope: str = "", n_hot: int = 25) -> str:
    if vcd:
        sc = f"-scope {scope} " if scope else ""
        activities = f"read_power_activities {sc}-vcd {vcd}"
    else:
        activities = "# vectorless (no VCD supplied): default activities"
    return POWER_TCL.format(
        liberty=liberty, netlist=netlist, top=top,
        read_spef=f"read_spef {spef}" if spef else "# no spef (pre-route)",
        clock=clock, period=period_ns, activities=activities, n_hot=n_hot)


# ---- report parsing --------------------------------------------------------------

_GROUP_ROW = re.compile(
    r"^(?P<group>Sequential|Combinational|Clock|Macro|Pad)\s+"
    r"(?P<internal>[\d.eE+-]+)\s+(?P<switching>[\d.eE+-]+)\s+"
    r"(?P<leakage>[\d.eE+-]+)\s+(?P<total>[\d.eE+-]+)")
_TOTAL_ROW = re.compile(
    r"^Total\s+(?P<internal>[\d.eE+-]+)\s+(?P<switching>[\d.eE+-]+)\s+"
    r"(?P<leakage>[\d.eE+-]+)\s+(?P<total>[\d.eE+-]+)")
# instance rows in the INSTANCES section: 4 numbers then the instance name
_INST_ROW = re.compile(
    r"^\s*(?P<internal>\d[\d.eE+-]*)\s+(?P<switching>\d[\d.eE+-]*)\s+"
    r"(?P<leakage>\d[\d.eE+-]*)\s+(?P<total>\d[\d.eE+-]*)\s+"
    r"(?P<inst>[A-Za-z_$\\][\w$./\\\[\]]*)\s*$")
# report_activity_annotation counts: "vcd  13", "unannotated  168", ...
_ANNOT_ROW = re.compile(r"^\s*(?P<kind>vcd|saif|user|propagated|unannotated)"
                        r"\s+(?P<n>\d+)\s*$", re.IGNORECASE)


def _sections(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    cur = "head"
    buf: list[str] = []
    # sentinel accepts every brand era, so a report captured under an
    # earlier name still parses after a rename
    from ..brand import all_names
    _eras = "|".join(n.upper() for n in all_names())
    for ln in text.splitlines():
        m = re.match(rf"== (?:{_eras}) (\w+) ==", ln.strip())
        if m:
            out[cur] = "\n".join(buf)
            cur, buf = m.group(1).lower(), []
            continue
        buf.append(ln)
    out[cur] = "\n".join(buf)
    return out


def parse_power_report(text: str) -> dict:
    """Everything out of the marker-delimited STA run: group table, total,
    hottest instances, annotation stats."""
    sec = _sections(text)
    out: dict = {"groups": {}, "total": {}, "instances": [],
                 "annotation": {}}
    for ln in sec.get("power", "").splitlines():
        ln = ln.strip()
        gm = _GROUP_ROW.match(ln)
        if gm:
            out["groups"][gm["group"].lower()] = {
                "internal_w": float(gm["internal"]),
                "switching_w": float(gm["switching"]),
                "leakage_w": float(gm["leakage"]),
                "total_w": float(gm["total"])}
            continue
        tm = _TOTAL_ROW.match(ln)
        if tm:
            out["total"] = {"internal_w": float(tm["internal"]),
                            "switching_w": float(tm["switching"]),
                            "leakage_w": float(tm["leakage"]),
                            "total_w": float(tm["total"])}
    for ln in sec.get("instances", "").splitlines():
        im = _INST_ROW.match(ln)
        if im and im["inst"] not in ("Power", "(Watts)"):
            out["instances"].append({"instance": im["inst"],
                                     "internal_w": float(im["internal"]),
                                     "switching_w": float(im["switching"]),
                                     "total_w": float(im["total"])})
    counts: dict[str, int] = {}
    for ln in sec.get("annotation", "").splitlines():
        am = _ANNOT_ROW.match(ln)
        if am:
            counts[am["kind"].lower()] = int(am["n"])
    if counts:
        annotated = sum(n for k, n in counts.items() if k != "unannotated")
        total = annotated + counts.get("unannotated", 0)
        out["annotation"] = {
            **counts, "annotated": annotated,
            "rate_pct": round(100.0 * annotated / total, 1) if total else 0.0,
            "note": "unannotated interior pins get activities PROPAGATED "
                    "from the annotated boundary (ports + registers), not "
                    "defaults — a low raw rate with full register annotation "
                    "is still workload-driven"}
    if out["total"]:
        clk = out["groups"].get("clock", {}).get("total_w", 0.0)
        tot = out["total"]["total_w"]
        if tot > 0:
            out["clock_share_pct"] = round(100.0 * clk / tot, 1)
            for i in out["instances"]:
                i["pct"] = round(100.0 * i["total_w"] / tot, 1)
    return out


def aggregate_by_module(instances: list[dict]) -> dict[str, dict]:
    """Hot instances grouped by hierarchy prefix (flat designs collapse to
    the top module — the per-instance table is the useful view there)."""
    mods: dict[str, dict] = {}
    for i in instances:
        prefix = i["instance"].rsplit("/", 1)[0] if "/" in i["instance"] \
            else i["instance"].rsplit(".", 1)[0] if "." in i["instance"] \
            else "(top)"
        m = mods.setdefault(prefix, {"total_w": 0.0, "pct": 0.0, "n": 0})
        m["total_w"] = round(m["total_w"] + i["total_w"], 9)
        m["pct"] = round(m["pct"] + i.get("pct", 0.0), 2)
        m["n"] += 1
    return dict(sorted(mods.items(), key=lambda kv: -kv[1]["total_w"]))
