/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module counter(clk, rst_n, en, clr, count, tc);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input en;
  wire en;
  input clr;
  wire clr;
  output [7:0] count;
  wire [7:0] count;
  output tc;
  wire tc;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  sky130_fd_sc_hd__inv_2 _23_ (
    .A(count[5]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__inv_2 _24_ (
    .A(clr),
    .Y(_09_)
  );
  sky130_fd_sc_hd__and3_2 _25_ (
    .A(count[1]),
    .B(count[0]),
    .C(en),
    .X(_10_)
  );
  sky130_fd_sc_hd__and3_2 _26_ (
    .A(count[3]),
    .B(count[2]),
    .C(count[4]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2_2 _27_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and3_2 _28_ (
    .A(count[5]),
    .B(_10_),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__nand2_2 _29_ (
    .A(count[6]),
    .B(count[7]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__and3_2 _30_ (
    .A(count[6]),
    .B(count[7]),
    .C(_13_),
    .X(tc)
  );
  sky130_fd_sc_hd__a21oi_2 _31_ (
    .A1(count[0]),
    .A2(en),
    .B1(clr),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21a_2 _32_ (
    .A1(count[0]),
    .A2(en),
    .B1(_15_),
    .X(_00_)
  );
  sky130_fd_sc_hd__a21oi_2 _33_ (
    .A1(count[0]),
    .A2(en),
    .B1(count[1]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor3_2 _34_ (
    .A(clr),
    .B(_10_),
    .C(_16_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a21oi_2 _35_ (
    .A1(count[2]),
    .A2(_10_),
    .B1(clr),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o21a_2 _36_ (
    .A1(count[2]),
    .A2(_10_),
    .B1(_17_),
    .X(_02_)
  );
  sky130_fd_sc_hd__a21oi_2 _37_ (
    .A1(count[2]),
    .A2(_10_),
    .B1(count[3]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a311oi_2 _38_ (
    .A1(count[3]),
    .A2(count[2]),
    .A3(_10_),
    .B1(_18_),
    .C1(clr),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a31o_2 _39_ (
    .A1(count[3]),
    .A2(count[2]),
    .A3(_10_),
    .B1(count[4]),
    .X(_19_)
  );
  sky130_fd_sc_hd__and3_2 _40_ (
    .A(_09_),
    .B(_12_),
    .C(_19_),
    .X(_04_)
  );
  sky130_fd_sc_hd__a31o_2 _41_ (
    .A1(count[5]),
    .A2(_10_),
    .A3(_11_),
    .B1(clr),
    .X(_20_)
  );
  sky130_fd_sc_hd__a21oi_2 _42_ (
    .A1(_08_),
    .A2(_12_),
    .B1(_20_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a41o_2 _43_ (
    .A1(count[5]),
    .A2(count[6]),
    .A3(_10_),
    .A4(_11_),
    .B1(clr),
    .X(_21_)
  );
  sky130_fd_sc_hd__o21ba_2 _44_ (
    .A1(count[6]),
    .A2(_13_),
    .B1_N(_21_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a41o_2 _45_ (
    .A1(count[5]),
    .A2(count[6]),
    .A3(_10_),
    .A4(_11_),
    .B1(count[7]),
    .X(_22_)
  );
  sky130_fd_sc_hd__o311a_2 _46_ (
    .A1(_08_),
    .A2(_12_),
    .A3(_14_),
    .B1(_22_),
    .C1(_09_),
    .X(_07_)
  );
  sky130_fd_sc_hd__dfrtp_2 _47_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _48_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _49_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _50_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _51_ (
    .CLK(clk),
    .D(_04_),
    .Q(count[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _52_ (
    .CLK(clk),
    .D(_05_),
    .Q(count[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _53_ (
    .CLK(clk),
    .D(_06_),
    .Q(count[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _54_ (
    .CLK(clk),
    .D(_07_),
    .Q(count[7]),
    .RESET_B(rst_n)
  );
endmodule
